name: backend-ci

on:
  push:
    paths-ignore:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths-ignore:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ADMIN_API_KEY: test-key # we have set up this key in the tests 
      OPENAI_API_KEY: dummy # to avoid hitting real OpenAI during tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'            

      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests (with coverage & junit)
        working-directory: backend
        run: |
          pytest -q --cov=. --cov-report=xml --junitxml=pytest-report.xml

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: backend/coverage.xml
          if-no-files-found: warn

      - name: Upload junit report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: backend/pytest-report.xml
          if-no-files-found: warn
